server:
  port: 80

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: (username)
      password: (password)
      database: OnlineJudge
      authentication-database: admin

app:
  jwt:
    secret: (jwt secret)
    expirationDay: 30
  judge:
    containerName: oj-judge-container
    threadPoolSize: 4
