server:
  port: 80

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: (USERNAME)
      password: (PASSWORD)
      database: OnlineJudge
      authentication-database: admin

app:
  jwt:
    secret: (JWT SECRET - 256bit)
    expirationDay: 30
  judge:
    containerName: oj-judge-container
    threadPoolSize: 4
